@echo off
REM SonarScanner wrapper for BempDiff project
REM Generated by sonarqube-mcp skill - avoids PowerShell special characters issue
setlocal enabledelayedexpansion
set "SONAR_SCANNER_HOME=D:\code\sonar\sonar-scanner-8.0.1.6346-windows-x64"
set "PROJECT_HOME=%~dp0.."
"%SONAR_SCANNER_HOME%\bin\sonar-scanner.bat" -D "sonar.projectBaseDir=%PROJECT_HOME%" %*
endlocal