sonar.projectKey=bempdiff
sonar.projectName=BempDiff - Package Comparison Tool
sonar.projectVersion=1.0.0
sonar.sourceEncoding=UTF-8
sonar.sources=prototype/java_core/src,prototype/javafx_ui/src
sonar.java.binaries=prototype/java_core/out,prototype/javafx_ui/out
sonar.exclusions=prototype/java_core/demo_export/**,prototype/java_core_export/**,prototype/java_core_ai_replay/**,dist/**,prototype/toolchain/**,prototype/out/**,**/out_secure/**
sonar.java.libraries=prototype/toolchain/javafx-base-21-win.jar,prototype/toolchain/javafx-controls-21-win.jar,prototype/toolchain/javafx-fxml-21-win.jar,prototype/toolchain/javafx-graphics-21-win.jar,prototype/cfr.jar